server:
  port: 8600
spring:
  application:
    name: gateway-server
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: localhost:8849
      http-method-specify: true
    gateway:
      routes:
        - id: information-portal
          uri: lb://information-portal
          predicates:
            - Path=/api/v1/users/**,/api/v1/admin/**,/api/v1/userLinkCategory/**
          filters:
            - RewritePath=/api/v1/(?<segment>.*), /$\{segment}
        - id: training-and-learning
          uri: lb://training-and-learning
          predicates:
            - Path=/api/v1/comment/**, /api/v1/study/**
        - id: training-learning-video
          uri: lb://training-learning-video
          predicates:
            - Path=/api/v1/video/**
        - id: resource-management
          uri: lb://resource-management
          predicates:
            - Path=/api/v1/questionBank/**
        - id: exam-evaluation
          uri: lb://exam-evaluation
          predicates:
            - Path=/api/v1/examQuestion/**
  rabbitmq:
    host: localhost
    port: 5672
    virtual-host: /
    username: rabbitmq
    password: rabbitmq
    listener:
      direct:
        prefetch: 1
        acknowledge-mode: auto
        retry:
          enabled: true
          initial-interval: 1000ms
          multiplier: 1
          max-attempts: 3
          stateless: false
    connection-timeout: 1s
    template:
      retry:
        enabled: true
        initial-interval: 200ms # 间隔重连时间
        multiplier: 1 # 等待时间增长倍数
        max-attempts: 3 # 最大请求次数
  security:
    user:
      name: user
      password: 123
seata:
  tx-service-group: default  #这里每个服务都是对应不同的映射名,在配置中心可以看到
  registry:
    type: nacos
    nacos:
      server-addr: 127.0.0.1:8848
      group: SEATA_GROUP
      application: seata-server
  service:
    vgroup-mapping:
      #这里也要注意 key为映射名
      default: default

healthe:
  auth:
    exclude-paths:
      - /users/login/**
      - /study/**
      - /comment/**
      - /video/**
      - /admins/login/**
      - /questionBank/**
      - /users/statistic/**
      - /examQuestion/**
      - /userLinkCategory/**
    include-paths:
  jwt:
    location: classpath:healthe.jks
    alias: healthe
    password: healthe
    tokenTTL: 10m

